<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Municipios;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $municipios = [
            ['nombre' => 'Boaco', 'departamentos_id' => 1, 'estado' => 1],
            ['nombre' => 'Camoapa', 'departamentos_id' => 1, 'estado' => 1],
            ['nombre' => 'Santa Lucía', 'departamentos_id' => 1, 'estado' => 1],
            ['nombre' => 'San José Del Remate', 'departamentos_id' => 1, 'estado' => 1],
            ['nombre' => 'San Lorenzo', 'departamentos_id' => 1, 'estado' => 1],
            ['nombre' => 'Teustepe', 'departamentos_id' => 1, 'estado' => 1],
            ['nombre' => 'Jinotepe', 'departamentos_id' => 2, 'estado' => 1],
            ['nombre' => 'Diriamba', 'departamentos_id' => 2, 'estado' => 1],
            ['nombre' => 'San Marcos', 'departamentos_id' => 2, 'estado' => 1],
            ['nombre' => 'Santa Teresa', 'departamentos_id' => 2, 'estado' => 1],
            ['nombre' => 'Dolores', 'departamentos_id' => 2, 'estado' => 1],
            ['nombre' => 'La Paz', 'departamentos_id' => 2, 'estado' => 1],
            ['nombre' => 'Carazo', 'departamentos_id' => 2, 'estado' => 1],
            ['nombre' => 'El Rosario', 'departamentos_id' => 2, 'estado' => 1],
            ['nombre' => 'La Conquista', 'departamentos_id' => 2, 'estado' => 1],
            ['nombre' => 'Chinandega', 'departamentos_id' => 3, 'estado' => 1],
            ['nombre' => 'Corinto', 'departamentos_id' => 3, 'estado' => 1],
            ['nombre' => 'El Realejo', 'departamentos_id' => 3, 'estado' => 1],
            ['nombre' => 'Chichigalpa', 'departamentos_id' => 3, 'estado' => 1],
            ['nombre' => 'Posoltega', 'departamentos_id' => 3, 'estado' => 1],
            ['nombre' => 'El Viejo', 'departamentos_id' => 3, 'estado' => 1],
            ['nombre' => 'Puerto Morazán', 'departamentos_id' => 3, 'estado' => 1],
            ['nombre' => 'Somotillo', 'departamentos_id' => 3, 'estado' => 1],
            ['nombre' => 'Villa Nueva', 'departamentos_id' => 3, 'estado' => 1],
            ['nombre' => 'Santo Tomás del Norte', 'departamentos_id' => 3, 'estado' => 1],
            ['nombre' => 'Cinco Pinos', 'departamentos_id' => 3, 'estado' => 1],
            ['nombre' => 'San Francisco Del Norte', 'departamentos_id' => 3, 'estado' => 1],
            ['nombre' => 'San Pedro Del Norte', 'departamentos_id' => 3, 'estado' => 1],
            ['nombre' => 'Juigalpa', 'departamentos_id' => 4, 'estado' => 1],
            ['nombre' => 'Acoyapa', 'departamentos_id' => 4, 'estado' => 1],
            ['nombre' => 'Santo Tomás', 'departamentos_id' => 4, 'estado' => 1],
            ['nombre' => 'Villa Sandino', 'departamentos_id' => 4, 'estado' => 1],
            ['nombre' => 'San Pedro de Lóvago', 'departamentos_id' => 4, 'estado' => 1],
            ['nombre' => 'La Libertad', 'departamentos_id' => 4, 'estado' => 1],
            ['nombre' => 'Santo Domingo', 'departamentos_id' => 4, 'estado' => 1],
            ['nombre' => 'Comalapa', 'departamentos_id' => 4, 'estado' => 1],
            ['nombre' => 'San Francisco Cuapa', 'departamentos_id' => 4, 'estado' => 1],
            ['nombre' => 'El Coral', 'departamentos_id' => 4, 'estado' => 1],
            ['nombre' => 'Estelí', 'departamentos_id' => 5, 'estado' => 1],
            ['nombre' => 'Pueblo Nuevo', 'departamentos_id' => 5, 'estado' => 1],
            ['nombre' => 'Condega', 'departamentos_id' => 5, 'estado' => 1],
            ['nombre' => 'San Juan Limay', 'departamentos_id' => 5, 'estado' => 1],
            ['nombre' => 'La Trinidad', 'departamentos_id' => 5, 'estado' => 1],
            ['nombre' => 'San Nicolás', 'departamentos_id' => 5, 'estado' => 1],
            ['nombre' => 'Granada', 'departamentos_id' => 6, 'estado' => 1],
            ['nombre' => 'Nandaime', 'departamentos_id' => 6, 'estado' => 1],
            ['nombre' => 'Diriomo', 'departamentos_id' => 6, 'estado' => 1],
            ['nombre' => 'Diriá', 'departamentos_id' => 6, 'estado' => 1],
            ['nombre' => 'Jinotega', 'departamentos_id' => 7, 'estado' => 1],
            ['nombre' => 'San Rafael Del Norte', 'departamentos_id' => 7, 'estado' => 1],
            ['nombre' => 'San Sebastián Yalí', 'departamentos_id' => 7, 'estado' => 1],
            ['nombre' => 'La Concordia', 'departamentos_id' => 7, 'estado' => 1],
            ['nombre' => 'San José De Bocay', 'departamentos_id' => 7, 'estado' => 1],
            ['nombre' => 'El Cuá Bocay', 'departamentos_id' => 7, 'estado' => 1],
            ['nombre' => 'Santa María Pantasma', 'departamentos_id' => 7, 'estado' => 1],
            ['nombre' => 'León', 'departamentos_id' => 8, 'estado' => 1],
            ['nombre' => 'El Jicaral', 'departamentos_id' => 8, 'estado' => 1],
            ['nombre' => 'La Paz Centro', 'departamentos_id' => 8, 'estado' => 1],
            ['nombre' => 'Santa Rosa Del Peñón', 'departamentos_id' => 8, 'estado' => 1],
            ['nombre' => 'Quetzalguaque', 'departamentos_id' => 8, 'estado' => 1],
            ['nombre' => 'Nagarote', 'departamentos_id' => 8, 'estado' => 1],
            ['nombre' => 'El Sauce', 'departamentos_id' => 8, 'estado' => 1],
            ['nombre' => 'Achuapa', 'departamentos_id' => 8, 'estado' => 1],
            ['nombre' => 'Telica', 'departamentos_id' => 8, 'estado' => 1],
            ['nombre' => 'Larreynaga Malpaisillo', 'departamentos_id' => 8, 'estado' => 1],
            ['nombre' => 'Somoto', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'Telpaneca', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'San Juan Río Coco', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'Palacagüina', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'Yalagüina', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'Totogalpa', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'San Lucas', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'La Sabanas', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'San José De Cusmapa', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'Somoto', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'Telpaneca', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'San Juan Río Coco', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'Palacagüina', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'Yalagüina', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'Totogalpa', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'San Lucas', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'La Sabanas', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'San José De Cusmapa', 'departamentos_id' => 9, 'estado' => 1],
            ['nombre' => 'Managua', 'departamentos_id' => 10,  'estado' => 1],
            ['nombre' => 'Tipitapa', 'departamentos_id' => 10,  'estado' => 1],
            ['nombre' => 'Ciudad Sandino', 'departamentos_id' => 10,  'estado' => 1],
            ['nombre' => 'San Rafael del Sur', 'departamentos_id' => 10,  'estado' => 1],
            ['nombre' => 'Villa El Carmen', 'departamentos_id' => 10, 'estado' => 1],
            ['nombre' => 'Mateare', 'departamentos_id' => 10, 'estado' => 1],
            ['nombre' => 'Ticuantepe', 'departamentos_id' => 10,  'estado' => 1],
            ['nombre' => 'El Crucero', 'departamentos_id' => 10, 'estado' => 1],
            ['nombre' => 'San Francisco Libre', 'departamentos_id' => 10,  'estado' => 1],
            ['nombre' => 'Masaya', 'departamentos_id' => 11,  'estado' => 1],
            ['nombre' => 'Masatepe', 'departamentos_id' => 11, 'estado' => 1],
            ['nombre' => 'Nindirí', 'departamentos_id' => 11,  'estado' => 1],
            ['nombre' => 'La Concepción', 'departamentos_id' => 11,  'estado' => 1],
            ['nombre' => 'Niquinohomo', 'departamentos_id' => 11,  'estado' => 1],
            ['nombre' => 'Nandasmo', 'departamentos_id' => 11, 'estado' => 1],
            ['nombre' => 'Tisma', 'departamentos_id' => 11,  'estado' => 1],
            ['nombre' => 'Catarina', 'departamentos_id' => 11,  'estado' => 1],
            ['nombre' => 'San Juan de Oriente', 'departamentos_id' => 11,  'estado' => 1],
            ['nombre' => 'Matagalpa', 'departamentos_id' => 12,  'estado' => 1],
            ['nombre' => 'El Tuma-La Dalia', 'departamentos_id' => 12,  'estado' => 1],
            ['nombre' => 'Matiguás', 'departamentos_id' => 12,  'estado' => 1],
            ['nombre' => 'Ciudad Darío', 'departamentos_id' => 12, 'estado' => 1],
            ['nombre' => 'Sébaco', 'departamentos_id' => 12, 'estado' => 1],
            ['nombre' => 'Río Blanco', 'departamentos_id' => 12,  'estado' => 1],
            ['nombre' => 'San Ramón', 'departamentos_id' => 12, 'estado' => 1],
            ['nombre' => 'Rancho Grande', 'departamentos_id' => 12,  'estado' => 1],
            ['nombre' => 'San Isidro', 'departamentos_id' => 12,  'estado' => 1],
            ['nombre' => 'San Dionisio', 'departamentos_id' => 12,  'estado' => 1],
            ['nombre' => 'Esquipulas', 'departamentos_id' => 12,  'estado' => 1],
            ['nombre' => 'Muy Muy', 'departamentos_id' => 12,  'estado' => 1],
            ['nombre' => 'Terrabona', 'departamentos_id' => 12, 'estado' => 1],
            ['nombre' => 'Jalapa', 'departamentos_id' => 13,  'estado' => 1],
            ['nombre' => 'Ocotal', 'departamentos_id' => 13, 'estado' => 1],
            ['nombre' => 'Quilalí', 'departamentos_id' => 13,  'estado' => 1],
            ['nombre' => 'El Jícaro', 'departamentos_id' => 13, 'estado' => 1],
            ['nombre' => 'Wiwilí de Nueva Segovia', 'departamentos_id' => 13, 'estado' => 1],
            ['nombre' => 'Murra', 'departamentos_id' => 13,  'estado' => 1],
            ['nombre' => 'San Fernando', 'departamentos_id' => 13,  'estado' => 1],
            ['nombre' => 'Mozonte', 'departamentos_id' => 13, 'estado' => 1],
            ['nombre' => 'Macuelizo', 'departamentos_id' => 13,  'estado' => 1],
            ['nombre' => 'Dipilto', 'departamentos_id' => 13,  'estado' => 1],
            ['nombre' => 'Ciudad Antigua', 'departamentos_id' => 13, 'estado' => 1],
            ['nombre' => 'Santa María', 'departamentos_id' => 13, 'estado' => 1],
            ['nombre' => 'San Carlos', 'departamentos_id' => 14, 'estado' => 1],
            ['nombre' => 'El Castillo', 'departamentos_id' => 14,  'estado' => 1],
            ['nombre' => 'San Miguelito', 'departamentos_id' => 14,  'estado' => 1],
            ['nombre' => 'El Almendro', 'departamentos_id' => 14,  'estado' => 1],
            ['nombre' => 'Morrito', 'departamentos_id' => 14,  'estado' => 1],
            ['nombre' => 'San Juan de Nicaragua', 'departamentos_id' => 14, 'estado' => 1],
            ['nombre' => 'Rivas', 'departamentos_id' => 15, 'estado' => 1],
            ['nombre' => 'Tola', 'departamentos_id' => 15, 'estado' => 1],
            ['nombre' => 'Altagracia', 'departamentos_id' => 15, 'estado' => 1],
            ['nombre' => 'Belén', 'departamentos_id' => 15,  'estado' => 1],
            ['nombre' => 'San Juan del Sur', 'departamentos_id' => 15,  'estado' => 1],
            ['nombre' => 'Potosí', 'departamentos_id' => 15, 'estado' => 1],
            ['nombre' => 'Moyogalpa', 'departamentos_id' => 15, 'estado' => 1],
            ['nombre' => 'San Jorge', 'departamentos_id' => 15,  'estado' => 1],
            ['nombre' => 'Cárdenas', 'departamentos_id' => 15, 'estado' => 1],
            ['nombre' => 'Buenos Aires', 'departamentos_id' => 15, 'estado' => 1],
            ['nombre' => 'Puerto Cabezas', 'departamentos_id' => 16,  'estado' => 1],
            ['nombre' => 'Siuna', 'departamentos_id' => 16,  'estado' => 1],
            ['nombre' => 'Waslala', 'departamentos_id' => 16, 'estado' => 1],
            ['nombre' => 'Waspán', 'departamentos_id' => 16,  'estado' => 1],
            ['nombre' => 'Mulukukú', 'departamentos_id' => 16, 'estado' => 1],
            ['nombre' => 'Rosita', 'departamentos_id' => 16, 'estado' => 1],
            ['nombre' => 'Bonanza', 'departamentos_id' => 16,  'estado' => 1],
            ['nombre' => 'Prinzapolka', 'departamentos_id' => 16, 'estado' => 1],
            ['nombre' => 'Nueva Guinea', 'departamentos_id' => 17,  'estado' => 1],
            ['nombre' => 'El Rama', 'departamentos_id' => 17, 'estado' => 1],
            ['nombre' => 'Bluefields', 'departamentos_id' => 17, 'estado' => 1],
            ['nombre' => 'Paiwas', 'departamentos_id' => 17, 'estado' => 1],
            ['nombre' => 'La Cruz de Río Grande', 'departamentos_id' => 17,  'estado' => 1],
            ['nombre' => 'El Tortuguero', 'departamentos_id' => 17,  'estado' => 1],
            ['nombre' => 'Muelle de los Bueyes', 'departamentos_id' => 17,  'estado' => 1],
            ['nombre' => 'El Ayote', 'departamentos_id' => 17, 'estado' => 1],
            ['nombre' => 'Laguna de Perlas', 'departamentos_id' => 17, 'estado' => 1],
            ['nombre' => 'Kukra-Hill', 'departamentos_id' => 17, 'estado' => 1],
            ['nombre' => 'Corn Island', 'departamentos_id' => 17,  'estado' => 1],
            ['nombre' => 'Desembocadura de Río Grande', 'departamentos_id' => 17,  'estado' => 1]

        ];
        foreach ($municipios as $municipios) {
            Municipios::create($municipios);
        }
    }
}
