<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Pais;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paises = [
            ['nombre' => 'Albania', 'codigo' => 'AL', 'estado' => 1],
            ['nombre' => 'Alemania', 'codigo' => 'DE', 'estado' => 1],
            ['nombre' => 'Andorra', 'codigo' => 'AD', 'estado' => 1],
            ['nombre' => 'Austria', 'codigo' => 'AT', 'estado' => 1],
            ['nombre' => 'Bélgica', 'codigo' => 'BE', 'estado' => 1],
            ['nombre' => 'Bielorrusia', 'codigo' => 'BY', 'estado' => 1],
            ['nombre' => 'Bosnia y Herzegovina', 'codigo' => 'BA', 'estado' => 1],
            ['nombre' => 'Bulgaria', 'codigo' => 'BG', 'estado' => 1],
            ['nombre' => 'Croacia', 'codigo' => 'HR', 'estado' => 1],
            ['nombre' => 'Chipre', 'codigo' => 'CY', 'estado' => 1],
            ['nombre' => 'Dinamarca', 'codigo' => 'DK', 'estado' => 1],
            ['nombre' => 'Eslovaquia', 'codigo' => 'SK', 'estado' => 1],
            ['nombre' => 'Eslovenia', 'codigo' => 'SI', 'estado' => 1],
            ['nombre' => 'España', 'codigo' => 'ES', 'estado' => 1],
            ['nombre' => 'Estonia', 'codigo' => 'EE', 'estado' => 1],
            ['nombre' => 'Finlandia', 'codigo' => 'FI', 'estado' => 1],
            ['nombre' => 'Francia', 'codigo' => 'FR', 'estado' => 1],
            ['nombre' => 'Grecia', 'codigo' => 'GR', 'estado' => 1],
            ['nombre' => 'Hungría', 'codigo' => 'HU', 'estado' => 1],
            ['nombre' => 'Irlanda', 'codigo' => 'IE', 'estado' => 1],
            ['nombre' => 'Islandia', 'codigo' => 'IS', 'estado' => 1],
            ['nombre' => 'Italia', 'codigo' => 'IT', 'estado' => 1],
            ['nombre' => 'Letonia', 'codigo' => 'LV', 'estado' => 1],
            ['nombre' => 'Liechtenstein', 'codigo' => 'LI', 'estado' => 1],
            ['nombre' => 'Lituania', 'codigo' => 'LT', 'estado' => 1],
            ['nombre' => 'Luxemburgo', 'codigo' => 'LU', 'estado' => 1],
            ['nombre' => 'Malta', 'codigo' => 'MT', 'estado' => 1],
            ['nombre' => 'Moldavia', 'codigo' => 'MD', 'estado' => 1],
            ['nombre' => 'Mónaco', 'codigo' => 'MC', 'estado' => 1],
            ['nombre' => 'Montenegro', 'codigo' => 'ME', 'estado' => 1],
            ['nombre' => 'Noruega', 'codigo' => 'NO', 'estado' => 1],
            ['nombre' => 'Países Bajos', 'codigo' => 'NL', 'estado' => 1],
            ['nombre' => 'Polonia', 'codigo' => 'PL', 'estado' => 1],
            ['nombre' => 'Portugal', 'codigo' => 'PT', 'estado' => 1],
            ['nombre' => 'Reino Unido', 'codigo' => 'GB', 'estado' => 1],
            ['nombre' => 'República Checa', 'codigo' => 'CZ', 'estado' => 1],
            ['nombre' => 'Rumanía', 'codigo' => 'RO', 'estado' => 1],
            ['nombre' => 'Rusia', 'codigo' => 'RU', 'estado' => 1],
            ['nombre' => 'San Marino', 'codigo' => 'SM', 'estado' => 1],
            ['nombre' => 'Serbia', 'codigo' => 'RS', 'estado' => 1],
            ['nombre' => 'Suecia', 'codigo' => 'SE', 'estado' => 1],
            ['nombre' => 'Suiza', 'codigo' => 'CH', 'estado' => 1],
            ['nombre' => 'Ucrania', 'codigo' => 'UA', 'estado' => 1],
            ['nombre' => 'Vaticano', 'codigo' => 'VA', 'estado' => 1],
            ['nombre' => 'Argelia', 'codigo' => 'DZ', 'estado' => 1],
            ['nombre' => 'Angola', 'codigo' => 'AO', 'estado' => 1],
            ['nombre' => 'Benín', 'codigo' => 'BJ', 'estado' => 1],
            ['nombre' => 'Botsuana', 'codigo' => 'BW', 'estado' => 1],
            ['nombre' => 'Burkina Faso', 'codigo' => 'BF', 'estado' => 1],
            ['nombre' => 'Burundi', 'codigo' => 'BI', 'estado' => 1],
            ['nombre' => 'Cabo Verde', 'codigo' => 'CV', 'estado' => 1],
            ['nombre' => 'Camerún', 'codigo' => 'CM', 'estado' => 1],
            ['nombre' => 'Chad', 'codigo' => 'TD', 'estado' => 1],
            ['nombre' => 'Comoras', 'codigo' => 'KM', 'estado' => 1],
            ['nombre' => 'Congo', 'codigo' => 'CG', 'estado' => 1],
            ['nombre' => 'Costa de Marfil', 'codigo' => 'CI', 'estado' => 1],
            ['nombre' => 'Egipto', 'codigo' => 'EG', 'estado' => 1],
            ['nombre' => 'Eritrea', 'codigo' => 'ER', 'estado' => 1],
            ['nombre' => 'Eswatini', 'codigo' => 'SZ', 'estado' => 1],
            ['nombre' => 'Etiopía', 'codigo' => 'ET', 'estado' => 1],
            ['nombre' => 'Gabón', 'codigo' => 'GA', 'estado' => 1],
            ['nombre' => 'Gambia', 'codigo' => 'GM', 'estado' => 1],
            ['nombre' => 'Ghana', 'codigo' => 'GH', 'estado' => 1],
            ['nombre' => 'Guinea', 'codigo' => 'GN', 'estado' => 1],
            ['nombre' => 'Guinea-Bissau', 'codigo' => 'GW', 'estado' => 1],
            ['nombre' => 'Guinea Ecuatorial', 'codigo' => 'GQ', 'estado' => 1],
            ['nombre' => 'Kenia', 'codigo' => 'KE', 'estado' => 1],
            ['nombre' => 'Lesoto', 'codigo' => 'LS', 'estado' => 1],
            ['nombre' => 'Liberia', 'codigo' => 'LR', 'estado' => 1],
            ['nombre' => 'Libia', 'codigo' => 'LY', 'estado' => 1],
            ['nombre' => 'Madagascar', 'codigo' => 'MG', 'estado' => 1],
            ['nombre' => 'Malawi', 'codigo' => 'MW', 'estado' => 1],
            ['nombre' => 'Malí', 'codigo' => 'ML', 'estado' => 1],
            ['nombre' => 'Marruecos', 'codigo' => 'MA', 'estado' => 1],
            ['nombre' => 'Mauricio', 'codigo' => 'MU', 'estado' => 1],
            ['nombre' => 'Mauritania', 'codigo' => 'MR', 'estado' => 1],
            ['nombre' => 'Mozambique', 'codigo' => 'MZ', 'estado' => 1],
            ['nombre' => 'Namibia', 'codigo' => 'NA', 'estado' => 1],
            ['nombre' => 'Níger', 'codigo' => 'NE', 'estado' => 1],
            ['nombre' => 'Nigeria', 'codigo' => 'NG', 'estado' => 1],
            ['nombre' => 'República Centroafricana', 'codigo' => 'CF', 'estado' => 1],
            ['nombre' => 'República Democrática del Congo', 'codigo' => 'CD', 'estado' => 1],
            ['nombre' => 'Ruanda', 'codigo' => 'RW', 'estado' => 1],
            ['nombre' => 'Santo Tomé y Príncipe', 'codigo' => 'ST', 'estado' => 1],
            ['nombre' => 'Senegal', 'codigo' => 'SN', 'estado' => 1],
            ['nombre' => 'Seychelles', 'codigo' => 'SC', 'estado' => 1],
            ['nombre' => 'Sierra Leona', 'codigo' => 'SL', 'estado' => 1],
            ['nombre' => 'Somalia', 'codigo' => 'SO', 'estado' => 1],
            ['nombre' => 'Sudáfrica', 'codigo' => 'ZA', 'estado' => 1],
            ['nombre' => 'Sudán', 'codigo' => 'SD', 'estado' => 1],
            ['nombre' => 'Sudán del Sur', 'codigo' => 'SS', 'estado' => 1],
            ['nombre' => 'Tanzania', 'codigo' => 'TZ', 'estado' => 1],
            ['nombre' => 'Togo', 'codigo' => 'TG', 'estado' => 1],
            ['nombre' => 'Túnez', 'codigo' => 'TN', 'estado' => 1],
            ['nombre' => 'Uganda', 'codigo' => 'UG', 'estado' => 1],
            ['nombre' => 'Yibuti', 'codigo' => 'DJ', 'estado' => 1],
            ['nombre' => 'Zambia', 'codigo' => 'ZM', 'estado' => 1],
            ['nombre' => 'Zimbabue', 'codigo' => 'ZW', 'estado' => 1],
            ['nombre' => 'Afganistán', 'codigo' => 'AF', 'estado' => 1],
            ['nombre' => 'Arabia Saudita', 'codigo' => 'SA', 'estado' => 1],
            ['nombre' => 'Armenia', 'codigo' => 'AM', 'estado' => 1],
            ['nombre' => 'Azerbaiyán', 'codigo' => 'AZ', 'estado' => 1],
            ['nombre' => 'Bangladés', 'codigo' => 'BD', 'estado' => 1],
            ['nombre' => 'Baréin', 'codigo' => 'BH', 'estado' => 1],
            ['nombre' => 'Birmania', 'codigo' => 'MM', 'estado' => 1],
            ['nombre' => 'Brunéi', 'codigo' => 'BN', 'estado' => 1],
            ['nombre' => 'Bután', 'codigo' => 'BT', 'estado' => 1],
            ['nombre' => 'Camboya', 'codigo' => 'KH', 'estado' => 1],
            ['nombre' => 'Catar', 'codigo' => 'QA', 'estado' => 1],
            ['nombre' => 'China', 'codigo' => 'CN', 'estado' => 1],
            ['nombre' => 'Corea del Norte', 'codigo' => 'KP', 'estado' => 1],
            ['nombre' => 'Corea del Sur', 'codigo' => 'KR', 'estado' => 1],
            ['nombre' => 'Emiratos Árabes Unidos', 'codigo' => 'AE', 'estado' => 1],
            ['nombre' => 'Filipinas', 'codigo' => 'PH', 'estado' => 1],
            ['nombre' => 'Georgia', 'codigo' => 'GE', 'estado' => 1],
            ['nombre' => 'India', 'codigo' => 'IN', 'estado' => 1],
            ['nombre' => 'Indonesia', 'codigo' => 'ID', 'estado' => 1],
            ['nombre' => 'Iraq', 'codigo' => 'IQ', 'estado' => 1],
            ['nombre' => 'Irán', 'codigo' => 'IR', 'estado' => 1],
            ['nombre' => 'Israel', 'codigo' => 'IL', 'estado' => 1],
            ['nombre' => 'Japón', 'codigo' => 'JP', 'estado' => 1],
            ['nombre' => 'Jordania', 'codigo' => 'JO', 'estado' => 1],
            ['nombre' => 'Kazajistán', 'codigo' => 'KZ', 'estado' => 1],
            ['nombre' => 'Kirguistán', 'codigo' => 'KG', 'estado' => 1],
            ['nombre' => 'Kuwait', 'codigo' => 'KW', 'estado' => 1],
            ['nombre' => 'Laos', 'codigo' => 'LA', 'estado' => 1],
            ['nombre' => 'Líbano', 'codigo' => 'LB', 'estado' => 1],
            ['nombre' => 'Malasia', 'codigo' => 'MY', 'estado' => 1],
            ['nombre' => 'Maldivas', 'codigo' => 'MV', 'estado' => 1],
            ['nombre' => 'Mongolia', 'codigo' => 'MN', 'estado' => 1],
            ['nombre' => 'Nepal', 'codigo' => 'NP', 'estado' => 1],
            ['nombre' => 'Omán', 'codigo' => 'OM', 'estado' => 1],
            ['nombre' => 'Pakistán', 'codigo' => 'PK', 'estado' => 1],
            ['nombre' => 'Palestina', 'codigo' => 'PS', 'estado' => 1],
            ['nombre' => 'Singapur', 'codigo' => 'SG', 'estado' => 1],
            ['nombre' => 'Siria', 'codigo' => 'SY', 'estado' => 1],
            ['nombre' => 'Sri Lanka', 'codigo' => 'LK', 'estado' => 1],
            ['nombre' => 'Tailandia', 'codigo' => 'TH', 'estado' => 1],
            ['nombre' => 'Tayikistán', 'codigo' => 'TJ', 'estado' => 1],
            ['nombre' => 'Timor Oriental', 'codigo' => 'TL', 'estado' => 1],
            ['nombre' => 'Turkmenistán', 'codigo' => 'TM', 'estado' => 1],
            ['nombre' => 'Turquía', 'codigo' => 'TR', 'estado' => 1],
            ['nombre' => 'Uzbekistán', 'codigo' => 'UZ', 'estado' => 1],
            ['nombre' => 'Vietnam', 'codigo' => 'VN', 'estado' => 1],
            ['nombre' => 'Yemen', 'codigo' => 'YE', 'estado' => 1],
            ['nombre' => 'Australia', 'codigo' => 'AU', 'estado' => 1],
            ['nombre' => 'Fiyi', 'codigo' => 'FJ', 'estado' => 1],
            ['nombre' => 'Islas Marshall', 'codigo' => 'MH', 'estado' => 1],
            ['nombre' => 'Islas Salomón', 'codigo' => 'SB', 'estado' => 1],
            ['nombre' => 'Kiribati', 'codigo' => 'KI', 'estado' => 1],
            ['nombre' => 'Micronesia', 'codigo' => 'FM', 'estado' => 1],
            ['nombre' => 'Nauru', 'codigo' => 'NR', 'estado' => 1],
            ['nombre' => 'Nueva Zelanda', 'codigo' => 'NZ', 'estado' => 1],
            ['nombre' => 'Palaos', 'codigo' => 'PW', 'estado' => 1],
            ['nombre' => 'Papúa Nueva Guinea', 'codigo' => 'PG', 'estado' => 1],
            ['nombre' => 'Samoa', 'codigo' => 'WS', 'estado' => 1],
            ['nombre' => 'Tonga', 'codigo' => 'TO', 'estado' => 1],
            ['nombre' => 'Tuvalu', 'codigo' => 'TV', 'estado' => 1],
            ['nombre' => 'Vanuatu', 'codigo' => 'VU', 'estado' => 1],
            ['nombre' => 'Canadá', 'codigo' => 'CA', 'estado' => 1],
            ['nombre' => 'Estados Unidos', 'codigo' => 'US', 'estado' => 1],
            ['nombre' => 'México', 'codigo' => 'MX', 'estado' => 1],
            ['nombre' => 'Belice', 'codigo' => 'BZ', 'estado' => 1],
            ['nombre' => 'Costa Rica', 'codigo' => 'CR', 'estado' => 1],
            ['nombre' => 'El Salvador', 'codigo' => 'SV', 'estado' => 1],
            ['nombre' => 'Guatemala', 'codigo' => 'GT', 'estado' => 1],
            ['nombre' => 'Honduras', 'codigo' => 'HN', 'estado' => 1],
            ['nombre' => 'Nicaragua', 'codigo' => 'NI', 'estado' => 1],
            ['nombre' => 'Panamá', 'codigo' => 'PA', 'estado' => 1],
            ['nombre' => 'Anguila', 'codigo' => 'AI', 'estado' => 1],
            ['nombre' => 'Antigua y Barbuda', 'codigo' => 'AG', 'estado' => 1],
            ['nombre' => 'Aruba', 'codigo' => 'AW', 'estado' => 1],
            ['nombre' => 'Bahamas', 'codigo' => 'BS', 'estado' => 1],
            ['nombre' => 'Barbados', 'codigo' => 'BB', 'estado' => 1],
            ['nombre' => 'Bonaire', 'codigo' => 'BQ', 'estado' => 1],
            ['nombre' => 'Cuba', 'codigo' => 'CU', 'estado' => 1],
            ['nombre' => 'Curaçao', 'codigo' => 'CW', 'estado' => 1],
            ['nombre' => 'Dominica', 'codigo' => 'DM', 'estado' => 1],
            ['nombre' => 'Granada', 'codigo' => 'GD', 'estado' => 1],
            ['nombre' => 'Guadalupe', 'codigo' => 'GP', 'estado' => 1],
            ['nombre' => 'Haití', 'codigo' => 'HT', 'estado' => 1],
            ['nombre' => 'Islas Caimán', 'codigo' => 'KY', 'estado' => 1],
            ['nombre' => 'Islas Turcas y Caicos', 'codigo' => 'TC', 'estado' => 1],
            ['nombre' => 'Islas Vírgenes Británicas', 'codigo' => 'VG', 'estado' => 1],
            ['nombre' => 'Islas Vírgenes de los Estados Unidos', 'codigo' => 'VI', 'estado' => 1],
            ['nombre' => 'Jamaica', 'codigo' => 'JM', 'estado' => 1],
            ['nombre' => 'Martinica', 'codigo' => 'MQ', 'estado' => 1],
            ['nombre' => 'Montserrat', 'codigo' => 'MS', 'estado' => 1],
            ['nombre' => 'Puerto Rico', 'codigo' => 'PR', 'estado' => 1],
            ['nombre' => 'República Dominicana', 'codigo' => 'DO', 'estado' => 1],
            ['nombre' => 'San Bartolomé', 'codigo' => 'BL', 'estado' => 1],
            ['nombre' => 'San Cristóbal y Nieves', 'codigo' => 'KN', 'estado' => 1],
            ['nombre' => 'San Martín', 'codigo' => 'MF', 'estado' => 1],
            ['nombre' => 'San Vicente y las Granadinas', 'codigo' => 'VC', 'estado' => 1],
            ['nombre' => 'Santa Lucía', 'codigo' => 'LC', 'estado' => 1],
            ['nombre' => 'Trinidad y Tobago', 'codigo' => 'TT', 'estado' => 1],
            ['nombre' => 'Argentina', 'codigo' => 'AR', 'estado' => 1],
            ['nombre' => 'Bolivia', 'codigo' => 'BO', 'estado' => 1],
            ['nombre' => 'Brasil', 'codigo' => 'BR', 'estado' => 1],
            ['nombre' => 'Chile', 'codigo' => 'CL', 'estado' => 1],
            ['nombre' => 'Colombia', 'codigo' => 'CO', 'estado' => 1],
            ['nombre' => 'Ecuador', 'codigo' => 'EC', 'estado' => 1],
            ['nombre' => 'Guyana', 'codigo' => 'GY', 'estado' => 1],
            ['nombre' => 'Paraguay', 'codigo' => 'PY', 'estado' => 1],
            ['nombre' => 'Perú', 'codigo' => 'PE', 'estado' => 1],
            ['nombre' => 'Surinam', 'codigo' => 'SR', 'estado' => 1],
            ['nombre' => 'Uruguay', 'codigo' => 'UY', 'estado' => 1],
            ['nombre' => 'Venezuela', 'codigo' => 'VE', 'estado' => 1]
        ];
        foreach ($paises as $pais) {
            Pais::create($pais);
        }
    }
}
